spring:
    datasource:
        url: jdbc:mysql://awseb-e-qqnwj5ipty-stack-awsebrdsdatabase-j2h5sczzvxlg.c0kidhippwvw.ap-northeast-2.rds.amazonaws.com:3306/board?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
        username: ${rds.username}
        password: ${rds.password}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.MySQLDialect
                default_batch_fetch_size: 100
    cache:
        type: redis
        redis:
            host: simple-board-redis-0001-001.uwhc3k.0001.apse2.cache.amazonaws.com
            port: 6379
