spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/board?useSSL=false&serverTimezone=Asia/Seoul
#    username: root
#    password: 1234
    url: jdbc:mysql://awseb-e-qqnwj5ipty-stack-awsebrdsdatabase-j2h5sczzvxlg.c0kidhippwvw.ap-northeast-2.rds.amazonaws.com/board?useSSL=false&serverTimezone=Asia/Seoul
    username: jakeadmin
    password: ppthejake!00
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
      hibernate:
          ddl-auto: update
      show-sql: true
      properties:
        hibernate:
            format_sql: true
